# Docker Compose (Local)
# ===============================================
# Use this compose file if you want to run this
# MCP locally instead of reverse proxied
# ===============================================

services:
  mssql-mcp:
    container_name: mssql-mcp
    image: mssql-mcp:latest
    build: .
    restart: unless-stopped
    ports:
      - "8199:8199"
    networks:
      - mssql-loc
    env_file: .env.local

networks:
  mssql-loc:
    name: mssql-loc
    driver: bridge