services:
  mssql-mcp:
    container_name: mssql-mcp
    image: mssql-mcp:latest
    build: .
    restart: unless-stopped
    ports:
      - "8199:8199"
    networks:
      - mssql-loc
    env_file: .env

networks:
  mssql-loc:
    name: mssql-loc
    driver: bridge